### ISSUE TITLE
Write new test data load scripts

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#357]

**Comment by nrempel** [comment]
The script and test data has been added but currently relies on a locally running instance of permitify-x. Once we have a hosted version of permitify, we can point these scripts there.

**Comment by nrempel** [comment]
I've added the new category model and added logic to validate incoming categories on credentials.

I've opted to keep `type` a text field instead of an enum to allow for easier changes in the future since either would require application logic to handle the restriction.

https://github.com/bcgov/TheOrgBook/pull/373

The following configuration adds a category with some static data as an example:

```
    credential_types:
      - description: Incorporation
        schema: incorporation.bc_registries
        issuer_url: $APPLICATION_URL_INCORP
        topic: 
          source_id:
            input: corp_num
            from: claim
          type:
            input: incorporation
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: legal_name
                from: claim
              type:
                input: legal_name
                from: value
          - model: category
            fields:
              value:
                input: topic.status_active
                from: value
              type:
                input: topic_status
                from: value

```

![Screenshot 2018-07-26 13.35.30.png](https://images.zenhubusercontent.com/5ae8a5ee4b5806bc2bd15a54/b384d5ce-8235-486f-aa3f-0f2f3a4f1c5a)
