### ISSUE TITLE
Add categories with categories of type and status for topics

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#372]
**Use Case**: As a Registrar, I want to be able to display in the UI the type and status of a Topic so that a person browsing an organization can see that information on the Organization page of TheOrgBook.

Per discussion on a conference call with Ontario, the agreed to approach is:

* We'll add a "category" table parallel to name, address, etc. with at least the fields "type" and "value"
* Type will be an enumerated type defined in TheOrgBook - e.g. it will take a pull request to add a new enumerated value.  Initial types will the "TopicType" and "TopicStatus" (the exact names can be different)
* The table will be populated via the same Credentials Processor mapping as for the other tables.
* The incoming values should be made unique so that they can use i18n translation to present to the users in multiple languages. For example:
   * If the source system stores the status values as "1", "2" and "3", the system creating the credential should set the value to "org_status_1", "org_status_2" and "org_status_3" and i18n translation will make each of those codes user friendly in the user's current language.
   * If a new source system code is added (say "4"), the UI will display "org_status_4" until the i18n mappings are updated for the instance of TheOrgBook.

**Comment by nrempel** [comment]
I've added the new category model and added logic to validate incoming categories on credentials.

I've opted to keep `type` a text field instead of an enum to allow for easier changes in the future since either would require application logic to handle the restriction.

https://github.com/bcgov/TheOrgBook/pull/373

The following configuration adds a category with some static data as an example:

```
    credential_types:
      - description: Incorporation
        schema: incorporation.bc_registries
        issuer_url: $APPLICATION_URL_INCORP
        topic: 
          source_id:
            input: corp_num
            from: claim
          type:
            input: incorporation
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: legal_name
                from: claim
              type:
                input: legal_name
                from: value
          - model: category
            fields:
              value:
                input: topic.status_active
                from: value
              type:
                input: topic_status
                from: value

```

![Screenshot 2018-07-26 13.35.30.png](https://images.zenhubusercontent.com/5ae8a5ee4b5806bc2bd15a54/b384d5ce-8235-486f-aa3f-0f2f3a4f1c5a)
