### ISSUE TITLE
Handling of names and addresses in a single credential

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#399]
Ontario team ran into a problem when loading data into TEST  with the data loading scripts - `names` and `addresses` from a single business record in a data extract get assigned different `credential_id` when loading into TOB searchable database. the names table only has even credential_ids (2,4,6,8,10,etc) and the address table only has odd credential_ids (1,3,5,7,9,11,etc), this causes `names` appear without `addresses` in the UI

**Comment by nrempel** [comment]
I believe the issue here is that the topic is not being selected correctly.

https://github.com/weiiv/onbis-x/blob/master/config/services.yml

```
        topic:
          -
            parent_source_id:
              input: associated_company
              from: claim
            parent_type:
              input: incorporation
              from: value
            source_id:
              input: company_number
              from: claim
            type:
              input: doing_business_as
              from: value
          -
            source_id:
              input: company_number
              from: claim
            type:
              input: incorporation
              from: value
```

Example credentials:

```
[
   {
       "schema": "incorporation.onbis.gov.on.ca",
       "version": "1.0.32",
       "attributes": {
           "company_number": "513030",
           "company_name": "BELFOUNTAIN COMMUNITY TENNIS ASSOCIATION, INC.",
           "name_effective": "19820531",
           "company_status": "ONBIS_BUSINESS_STATUS_0",
           "status_effective": "19991118",
           "business_type": "ONBIS_BUSINESS_TYPE_G",
           "registered_jurisdiction": "ON",
           "extra_provincial": "N",
           "home_jurisdiction": "ONTARIO",
           "effective_date": "19820531",
           "end_date": ""
       }
   },
   {
       "schema": "address.onbis.gov.on.ca",
       "version": "1.0.32",
       "attributes": {
           "company_number": "513030",
           "associated_company": "",
           "addressee": "",
           "address_type": "REGISTERED/HEAD OFFICE ADDRESS",
           "civic_address": "6 MAPLE CRES.",
           "municipality": "HILLSBURGH",
           "province": "ON",
           "postal_code": "N0B 1Z0",
           "country": "CA",
           "effective_date": "",
           "end_date": ""
       }
   }
]
```

Currently, TheOrgBook only fails to "select" a topic if the primary topic fails; it doesn't care if the parent doesn't exist.

This allows an issuer to form relationships between organizations for an organization that or may not have *children* but _does not_ allow for a relationship to be conditionally created for organizations that may or _may not_ have *parents*.

Creating a failure condition for this to ensure that the full topic selector is accurate is more explicit and more flexible to handle this case.
