### ISSUE TITLE
Change credential end_date to effective_date + revoked

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#420]
On incoming credential of a given type and cardinality:

- `effective_date` defaults to `now` and revoked `false`
- `effective_date` can be overwritten by claim values
- a new credential with `effective_date` < an existing credential is set to `revoked` = `true`
- all existing credentials with `effective_date` < new credential `effective_date` have their `revoked` set to `true`

von-x configuration requires a new `credential` key as a sibling to `topic` and `mapping`:

```yaml
credential:
  effective_date:
    input: org_effective_date
    from: claim
topic: 
  # ...
mapping:
  - model: name
    fields:
      # ...
  - model: category
    fields:
      # ...
```

If no configuration is set, default values will be used.

cc: @weiiv @swcurran @ianco
